# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-10 10:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(max_length=64)),
                ('version', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('format', models.CharField(max_length=8)),
                ('bytes', models.IntegerField()),
                ('url', models.URLField()),
                ('secure_url', models.URLField()),
                ('env', models.CharField(max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
