# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-10 10:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0004_auto_20161107_1627'),
        ('connections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='social_account',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='socialaccount.SocialAccount'),
            preserve_default=False,
        ),
    ]
