# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-27 16:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0004_auto_20161107_1627'),
        ('accounts', '0005_auto_20161127_1609'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='connection',
            unique_together=set([('owner', 'social_account')]),
        ),
    ]
